###############################################################
#  Generated by:      Cadence Encounter 13.13-s017_1
#  OS:                Linux x86_64(Host ID microelnsys)
#  Generated on:      Wed Sep  7 23:01:55 2016
#  Design:            dataPath
#  Command:           floorPlan -coreMarginsBy die -site FreePDK45_38x28_10R...
###############################################################

Version: 8

Head Box: 0.0000 0.0000 117.6900 117.6000
IO Box: 0.0000 0.0000 117.6900 117.6000
Core Box: 0.0000 0.0000 117.6900 117.6000
UseStdUtil: false

######################################################
#  DesignRoutingHalo: <space> <bottomLayerName> <topLayerName>
######################################################

######################################################
#  Core Rows Parameters:                             #
######################################################
Row Spacing = 0.000000
Row SpacingType = 2
Row Flip = 2
Core Row Site: FreePDK45_38x28_10R_NP_162NW_34O 

##############################################################################
#  DefRow: <name> <site> <x> <y> <orient> <num_x> <num_y> <step_x> <step_y>  #
##############################################################################
DefRow: ROW_0 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 0.0000 FS 619 1 0.1900 0.0000
DefRow: ROW_1 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 1.4000 N 619 1 0.1900 0.0000
DefRow: ROW_2 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 2.8000 FS 619 1 0.1900 0.0000
DefRow: ROW_3 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 4.2000 N 619 1 0.1900 0.0000
DefRow: ROW_4 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 5.6000 FS 619 1 0.1900 0.0000
DefRow: ROW_5 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 7.0000 N 619 1 0.1900 0.0000
DefRow: ROW_6 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 8.4000 FS 619 1 0.1900 0.0000
DefRow: ROW_7 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 9.8000 N 619 1 0.1900 0.0000
DefRow: ROW_8 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 11.2000 FS 619 1 0.1900 0.0000
DefRow: ROW_9 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 12.6000 N 619 1 0.1900 0.0000
DefRow: ROW_10 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 14.0000 FS 619 1 0.1900 0.0000
DefRow: ROW_11 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 15.4000 N 619 1 0.1900 0.0000
DefRow: ROW_12 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 16.8000 FS 619 1 0.1900 0.0000
DefRow: ROW_13 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 18.2000 N 619 1 0.1900 0.0000
DefRow: ROW_14 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 19.6000 FS 619 1 0.1900 0.0000
DefRow: ROW_15 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 21.0000 N 619 1 0.1900 0.0000
DefRow: ROW_16 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 22.4000 FS 619 1 0.1900 0.0000
DefRow: ROW_17 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 23.8000 N 619 1 0.1900 0.0000
DefRow: ROW_18 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 25.2000 FS 619 1 0.1900 0.0000
DefRow: ROW_19 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 26.6000 N 619 1 0.1900 0.0000
DefRow: ROW_20 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 28.0000 FS 619 1 0.1900 0.0000
DefRow: ROW_21 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 29.4000 N 619 1 0.1900 0.0000
DefRow: ROW_22 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 30.8000 FS 619 1 0.1900 0.0000
DefRow: ROW_23 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 32.2000 N 619 1 0.1900 0.0000
DefRow: ROW_24 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 33.6000 FS 619 1 0.1900 0.0000
DefRow: ROW_25 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 35.0000 N 619 1 0.1900 0.0000
DefRow: ROW_26 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 36.4000 FS 619 1 0.1900 0.0000
DefRow: ROW_27 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 37.8000 N 619 1 0.1900 0.0000
DefRow: ROW_28 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 39.2000 FS 619 1 0.1900 0.0000
DefRow: ROW_29 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 40.6000 N 619 1 0.1900 0.0000
DefRow: ROW_30 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 42.0000 FS 619 1 0.1900 0.0000
DefRow: ROW_31 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 43.4000 N 619 1 0.1900 0.0000
DefRow: ROW_32 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 44.8000 FS 619 1 0.1900 0.0000
DefRow: ROW_33 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 46.2000 N 619 1 0.1900 0.0000
DefRow: ROW_34 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 47.6000 FS 619 1 0.1900 0.0000
DefRow: ROW_35 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 49.0000 N 619 1 0.1900 0.0000
DefRow: ROW_36 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 50.4000 FS 619 1 0.1900 0.0000
DefRow: ROW_37 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 51.8000 N 619 1 0.1900 0.0000
DefRow: ROW_38 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 53.2000 FS 619 1 0.1900 0.0000
DefRow: ROW_39 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 54.6000 N 619 1 0.1900 0.0000
DefRow: ROW_40 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 56.0000 FS 619 1 0.1900 0.0000
DefRow: ROW_41 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 57.4000 N 619 1 0.1900 0.0000
DefRow: ROW_42 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 58.8000 FS 619 1 0.1900 0.0000
DefRow: ROW_43 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 60.2000 N 619 1 0.1900 0.0000
DefRow: ROW_44 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 61.6000 FS 619 1 0.1900 0.0000
DefRow: ROW_45 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 63.0000 N 619 1 0.1900 0.0000
DefRow: ROW_46 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 64.4000 FS 619 1 0.1900 0.0000
DefRow: ROW_47 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 65.8000 N 619 1 0.1900 0.0000
DefRow: ROW_48 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 67.2000 FS 619 1 0.1900 0.0000
DefRow: ROW_49 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 68.6000 N 619 1 0.1900 0.0000
DefRow: ROW_50 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 70.0000 FS 619 1 0.1900 0.0000
DefRow: ROW_51 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 71.4000 N 619 1 0.1900 0.0000
DefRow: ROW_52 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 72.8000 FS 619 1 0.1900 0.0000
DefRow: ROW_53 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 74.2000 N 619 1 0.1900 0.0000
DefRow: ROW_54 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 75.6000 FS 619 1 0.1900 0.0000
DefRow: ROW_55 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 77.0000 N 619 1 0.1900 0.0000
DefRow: ROW_56 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 78.4000 FS 619 1 0.1900 0.0000
DefRow: ROW_57 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 79.8000 N 619 1 0.1900 0.0000
DefRow: ROW_58 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 81.2000 FS 619 1 0.1900 0.0000
DefRow: ROW_59 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 82.6000 N 619 1 0.1900 0.0000
DefRow: ROW_60 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 84.0000 FS 619 1 0.1900 0.0000
DefRow: ROW_61 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 85.4000 N 619 1 0.1900 0.0000
DefRow: ROW_62 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 86.8000 FS 619 1 0.1900 0.0000
DefRow: ROW_63 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 88.2000 N 619 1 0.1900 0.0000
DefRow: ROW_64 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 89.6000 FS 619 1 0.1900 0.0000
DefRow: ROW_65 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 91.0000 N 619 1 0.1900 0.0000
DefRow: ROW_66 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 92.4000 FS 619 1 0.1900 0.0000
DefRow: ROW_67 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 93.8000 N 619 1 0.1900 0.0000
DefRow: ROW_68 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 95.2000 FS 619 1 0.1900 0.0000
DefRow: ROW_69 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 96.6000 N 619 1 0.1900 0.0000
DefRow: ROW_70 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 98.0000 FS 619 1 0.1900 0.0000
DefRow: ROW_71 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 99.4000 N 619 1 0.1900 0.0000
DefRow: ROW_72 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 100.8000 FS 619 1 0.1900 0.0000
DefRow: ROW_73 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 102.2000 N 619 1 0.1900 0.0000
DefRow: ROW_74 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 103.6000 FS 619 1 0.1900 0.0000
DefRow: ROW_75 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 105.0000 N 619 1 0.1900 0.0000
DefRow: ROW_76 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 106.4000 FS 619 1 0.1900 0.0000
DefRow: ROW_77 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 107.8000 N 619 1 0.1900 0.0000
DefRow: ROW_78 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 109.2000 FS 619 1 0.1900 0.0000
DefRow: ROW_79 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 110.6000 N 619 1 0.1900 0.0000
DefRow: ROW_80 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 112.0000 FS 619 1 0.1900 0.0000
DefRow: ROW_81 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 113.4000 N 619 1 0.1900 0.0000
DefRow: ROW_82 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 114.8000 FS 619 1 0.1900 0.0000
DefRow: ROW_83 FreePDK45_38x28_10R_NP_162NW_34O 0.0000 116.2000 N 619 1 0.1900 0.0000

######################################################
#  Track: dir start number space layer_num layer1 ...#
######################################################
Track: Y 1.6700 73 1.6000 1 10
Track: X 1.7750 69 1.6800 1 10
Track: X 0.9350 139 0.8400 1 9
Track: Y 1.6700 73 1.6000 1 9
Track: Y 0.9100 139 0.8400 1 8
Track: X 0.9350 139 0.8400 1 8
Track: X 0.3750 419 0.2800 1 7
Track: Y 0.9100 139 0.8400 1 7
Track: Y 0.3500 419 0.2800 1 6
Track: X 0.3750 419 0.2800 1 6
Track: X 0.3750 419 0.2800 1 5
Track: Y 0.3500 419 0.2800 1 5
Track: Y 0.0700 840 0.1400 1 4
Track: X 0.3750 419 0.2800 1 4
Track: X 0.0950 619 0.1900 1 3
Track: Y 0.0700 840 0.1400 1 3
Track: Y 0.0700 840 0.1400 1 2
Track: X 0.0950 619 0.1900 1 2
Track: X 0.0950 619 0.1900 1 1
Track: Y 0.0700 840 0.1400 1 1

######################################################
#  GCellGrid: dir start number space                 #
######################################################
GCellGrid: X 115.9950 2 1.6950
GCellGrid: X 0.0950 62 1.9000
GCellGrid: X 0.0000 2 0.0950
GCellGrid: Y 116.2700 2 1.3300
GCellGrid: Y 0.0700 84 1.4000
GCellGrid: Y 0.0000 2 0.0700

######################################################
#  SpareCell: cellName                               #
#  SpareInst: instName                               #
######################################################

###############################1p########################
#  <SelectiveBlockage>                                #
#     <cell name="cell_name" />                     #
#  </SelectiveBlockage                                #
#######################################################

######################################################
#  ScanGroup: groupName startPin stopPin             #
######################################################

######################################################
#  JtagCell:  leafCellName                           #
#  JtagInst:  <instName | HInstName>                 #
######################################################

######################################################################################
#  BlackBox: -cell <cell_name> { -size <x> <y> |  -area <um^2> | \                  #
#            -gatecount <count> <areapergate> <utilization> | \                     #
#            {-gateArea <gateAreaValue> [-macroArea <macroAreaValue>]} } \          #
#            [-minwidth <w> | -minheight <h> | -fixedwidh <w> | -fixedheight <h>] \ #
#            [-aspectratio <ratio>]                                                  #
#            [-boxList <nrConstraintBox>                                             #
#              ConstraintBox: <llx> <lly> <urx> <ury>                                #
#              ... ]                                                                 #
######################################################################################

#######################################################################################
#  <Blackboxes>                                                                       #
#     <Blackbox  cell=name  width=N height=N                                          #
#                { area=A | gatecount=N areaPerGate=A cellUtil=F |                    #
#                  gateArea=F {macroArea=F | macorList='str'} includeMacroArea={0|1}} #
#                [minWidth=N | minHeight=N | fixedWidh=N | fixedHeight=N]             #
#                [aspectRatio=R] >                                                    #
#         <Box llx=float lly=float urx=float ury=float /> ...                         #
#     </Blackbox>                                                                     #
#  </Blackboxes>                                                                      #
#######################################################################################

#########################################################
#  PhysicalNet: <name> [-pwr|-gnd|-tiehi|-tielo]        #
#########################################################
PhysicalNet: vdd -pwr
PhysicalNet: gnd -gnd

#########################################################
#  PhysicalInstance: <name> <cell> <orient> <llx> <lly> #
#########################################################

#####################################################################
#  Group: <group_name> <nrHinst> [-isPhyHier]                       #
#    <inst_name>                                                    #
#    ...                                                            #
#####################################################################

#####################################################################
#  Fence:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Region: <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Guide:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  SoftGuide: <name>                                                #
#    ...                                                            #
#####################################################################

###########################################################################
#  <Constraints>                                                          #
#     <Constraint  type="fence|guide|region|softguide"                    #
#                  readonly=1  name="blk_name">                           #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#     </Constraint>                                                       #
#  </Constraints>                                                         #
###########################################################################
###########################################################################
#  <HierarchicalPartitions>                                               #
#     <GlobalPinConstraints>                                              #
#         <PinSpacing spacing=val />                                      #
#         <PinWidth layer=layerId width=val />                            #
#         <PinDepth layer=layerId depth=val />                            #
#         <CornerToPinDistance distance=val />                            #
#     </GlobalPinConstraints>                                             #
#     <NetGroup name="group_name" nets=val spacing=val isOptOrder=val     #
#         isAltLayer=val isPffGroup=val isSpreadPin=val                   #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val >#
#         <Net name="net_name" /> ...                                     #
#     </NetGroup>                                                         #
#     <Partition name="ptn_name"  hinst="name"                            #
#         coreToLeft=fval coreToRight=fval coreToTop=fval                 #
#         coreToBottom=val pinSpacingNorth=val pinSpacingWest=val         #
#         pinSpacingSouth=val pinSpacingEast=val  blockedLayers=xval >    #
#         <TrackHalfPitch Horizontal=val Vertical=val />                  #
#         <SpacingHalo left=10.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <Clone hinst="hinst_name" orient=R0|R90|... />                  #
#         <PinLayer side="N|W|S|E" Metal1=yes Metal2=yes ... />           #
#         <RowSize cellHeight=1.0 railWidth=1.0 />                        #
#         <RoutingHalo sideSize=11.0 bottomLayer=M1 topLayer=M2  />       #
#         <SpacingHalo left=11.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <PinToCornerDistance  totalCorners=nrCorners >                  #
#            <Corner number=<cornerNumber> distance=<distance> /> ...     #
#         </PinToCornerDistance >                                         #
#         <PinSpacingArea llx=val lly=val urx=val ury=val spacing=val />  #
#         <LayerWidthDepth layer=layerId width=w depth=d />               #
#         <PinConstraint>                                                 #
#            <Pin name="pinName" >                                      #
#               <edge edgeNumber=val />                                   #
#               <spacing space=val />                                    #
#               <layer layerMap=xval />                                  #
#               <pinWidth width=val />                                   #
#               <pinDepth depth=val />                                   #
#               <location x=val y=val />                                 #
#            </Pin>                                                       #
#         </PinConstraint>                                                #
#     </Partition>                                                        #
#     <CellPinGroup name="group_name" cell="cell_name" pins=nr            #
#         spacing=val isOptOrder=val isAltLayer=val isSpreadPin=val       #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val >#
#         <GroupFTerm name="term_name" /> ...                             #
#     </CellPinGroup>                                                     #
#     <PartitionPinBlockage layerMap=x llx=1 lly=2 urx=3 ury=4 name="n" />#
#     <PinGuide name="name" boxes=num layerPriority=val cell="name" >     #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 layer=id /> ...         #
#     </PinGuide>                                                         #
#     <CellPtnCut name="name" cuts=Num >                                  #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 /> ...                  #
#     </CellPtnCut>                                                       #
#  </HierarchicalPartitions>                                              #
###########################################################################
<HierarchicalPartitions>
    <GlobalPinConstraints>
        <PinSpacing spacing=2 />
        <CornerToPinDistance distance=5 />
    </GlobalPinConstraints>
    <Partition name="dataPath" hinst="" coreToLeft=0.0000 coreToRight=0.0000 coreToTop=0.0000 coreToBottom=0.0000 pinSpacingNorth=-1 pinSpacingWest=-1 pinSpacingSouth=-1 pinSpacingEast=-1 blockedLayers=0x3ff >
	<PinLayer side="N" Metal2=yes Metal4=yes Metal6=yes Metal8=yes Metal10=yes />
	<PinLayer side="W" Metal3=yes Metal5=yes Metal7=yes Metal9=yes />
	<PinLayer side="S" Metal2=yes Metal4=yes Metal6=yes Metal8=yes Metal10=yes />
	<PinLayer side="E" Metal3=yes Metal5=yes Metal7=yes Metal9=yes />
    <PinToCornerDistance totalCorners=4 >
      <Corner number=0 distance=-1 />
      <Corner number=1 distance=-1 />
      <Corner number=2 distance=-1 />
      <Corner number=3 distance=-1 />
    </PinToCornerDistance>
    </Partition>
</HierarchicalPartitions>

######################################################
#  Instance: <name> <orient> <llx> <lly>             #
######################################################

#################################################################
#  Block: <name> <orient> [<llx> <lly>]                         #
#         [<haloLeftMargin>  <haloBottomMargin>                 #
#          <haloRightMargin> <haloTopMargin> <haloFromInstBox>] #
#         [<IsInstDefCovered> <IsInstPreplaced>]                #
#                                                               #
#  Block with INT_MAX loc is for recording the halo block with  #
#  non-prePlaced status                                         #
#################################################################

######################################################
#  BlockLayerObstruct: <name> <layerX> ...           #
######################################################

######################################################
#  FeedthroughBuffer: <instName>                     #
######################################################

#################################################################
#  <PlacementBlockages>                                         #
#     <Blockage name="blk_name" type="hard|soft|partial">       #
#       <Attr density=1.2 inst="inst_name" pushdown=yes />      #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </PlacementBlockages>                                        #
#################################################################

#################################################################
#  <SizeBlockages>                                             #
#     <Blockage name="blk_name">                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </SizeBlockages>                                            #
#################################################################

###########################################################################
#  <RouteBlockages>                                                       #
#     <Blockage name="blk_name" type="User|RouteGuide|PtnCut|WideWire">   #
#       <Attr spacing=1.2 drw=1.2 inst="name" pushdown=yes fills=yes />   #
#       <Layer type="route|cut|masterslice" id=layerNo />                 #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#       <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...  />                       #
#     </Blockage>                                                         #
#  </RouteBlockages>                                                      #
###########################################################################

######################################################
#  PrerouteAsObstruct: <layer_treated_as_obstruct>   #
######################################################
PrerouteAsObstruct: 0x3

######################################################
#  NetWeight: <net_name> <weight (in integer)>       #
######################################################

#################################################################
#  SprFile: <file_name>                                         #
#################################################################
SprFile: .dataPath12879.rs.fp.spr

##############################################################################
#  <IOPins>                                                                  #
#    <Pin name="pin_name" type="clock|power|ground|analog"                   #
#         status="covered|fixed|placed" is_special=1 >                       #
#      <Port>                                                                #
#        <Pref x=1 y=2 side="N|S|W|E|U|D" width=w depth=d orientation=val /> #
#        <Via name="via_name" x=1 y=2 />...                                  #
#        <Layer id=id spacing=1.2 drw=1.2>                                   #
#          <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#          <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...           />              #
#        </Layer> ...                                                        #
#      </Port>  ...                                                          #
#      <Antenna model=num type="name" value=float_num layer=num /> ...       #
#    </Pin> ...                                                              #
#  </IOPins>                                                                 #
##############################################################################


#####################################################################
#  <Property>                                                       #
#     <obj_type name="inst_name" >                                  #
#       <prop name="name" type=type_name value=val />               #
#       <Attr name="name" type=type_name value=val />               #
#     </obj_type>                                                   #
#  </Property>                                                      #
#  where:                                                           #
#       type is data type: Box, String, Int, PTR, Loc, double, Bits #
#       obj_type are: inst, Design, instTerm, Bump, cell, net       #
#####################################################################
<Properties>
  <Design name="dataPath">
  </Design>
</Properties>

################################################################################
#  NetProperties: <net_name> [-special] [-def_prop {int|dbl|str} <value>]...   #
################################################################################

##################################################################################
#    Feedthru info:                                                              #
# <Feedthrus>                                                                    #
#   <Feedthru>                                                                   #
#       <tsv llx=n lly=n urx=n ury=n />                                          #
#       <stackvia layer=z llx=n lly=n urx=n ury=n />                             #
#       <bump front=name back=name  />                                           #
#   </Feedthru>                                                                  #
#   <Feedthru>                                                                   #
#   <...>                                                                        #
#   </Feedthru>                                                                  #
# </Feedthrus>                                                                   #
################################################################################
